// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: comm.proto

package prototest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JSONData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID           int32  `protobuf:"varint,1,opt,name=ID,proto3" :"ID,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Desc         string `protobuf:"bytes,3,opt,name=Desc,proto3" json:"Desc,omitempty"`
	Executor     string `protobuf:"bytes,4,opt,name=Executor,proto3" json:"Executor,omitempty"`
	BlackboardID string `protobuf:"bytes,5,opt,name=BlackboardID,proto3" json:"BlackboardID,omitempty"`
	Root         *Root  `protobuf:"bytes,6,opt,name=Root,proto3" json:"Root,omitempty"`
}

func (x *JSONData) Reset() {
	*x = JSONData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JSONData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONData) ProtoMessage() {}

func (x *JSONData) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONData.ProtoReflect.Descriptor instead.
func (*JSONData) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{0}
}

func (x *JSONData) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *JSONData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JSONData) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *JSONData) GetExecutor() string {
	if x != nil {
		return x.Executor
	}
	return ""
}

func (x *JSONData) GetBlackboardID() string {
	if x != nil {
		return x.BlackboardID
	}
	return ""
}

func (x *JSONData) GetRoot() *Root {
	if x != nil {
		return x.Root
	}
	return nil
}

type Root struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         int32         `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	NodeName   string        `protobuf:"bytes,2,opt,name=NodeName,proto3" json:"NodeName,omitempty"`
	Desc       string        `protobuf:"bytes,3,opt,name=Desc,proto3" json:"Desc,omitempty"`
	Decorators []*Decorators `protobuf:"bytes,4,rep,name=Decorators,proto3" json:"Decorators,omitempty"`
	Children   []*Children   `protobuf:"bytes,5,rep,name=Children,proto3" json:"Children,omitempty"`
}

func (x *Root) Reset() {
	*x = Root{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Root) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Root) ProtoMessage() {}

func (x *Root) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Root.ProtoReflect.Descriptor instead.
func (*Root) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{1}
}

func (x *Root) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Root) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Root) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Root) GetDecorators() []*Decorators {
	if x != nil {
		return x.Decorators
	}
	return nil
}

func (x *Root) GetChildren() []*Children {
	if x != nil {
		return x.Children
	}
	return nil
}

type Decorators struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID                      int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	NodeName                string `protobuf:"bytes,2,opt,name=NodeName,proto3" json:"NodeName,omitempty"`
	FlowAbortMode           string `protobuf:"bytes,3,opt,name=FlowAbortMode,proto3" json:"FlowAbortMode,omitempty"`
	NumLoops                int32  `protobuf:"varint,4,opt,name=NumLoops,proto3" json:"NumLoops,omitempty"`
	InfiniteLoop            bool   `protobuf:"varint,5,opt,name=InfiniteLoop,proto3" json:"InfiniteLoop,omitempty"`
	InfiniteLoopTimeoutTime int32  `protobuf:"varint,6,opt,name=InfiniteLoopTimeoutTime,proto3" json:"InfiniteLoopTimeoutTime,omitempty"`
}

func (x *Decorators) Reset() {
	*x = Decorators{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Decorators) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decorators) ProtoMessage() {}

func (x *Decorators) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decorators.ProtoReflect.Descriptor instead.
func (*Decorators) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{2}
}

func (x *Decorators) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Decorators) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Decorators) GetFlowAbortMode() string {
	if x != nil {
		return x.FlowAbortMode
	}
	return ""
}

func (x *Decorators) GetNumLoops() int32 {
	if x != nil {
		return x.NumLoops
	}
	return 0
}

func (x *Decorators) GetInfiniteLoop() bool {
	if x != nil {
		return x.InfiniteLoop
	}
	return false
}

func (x *Decorators) GetInfiniteLoopTimeoutTime() int32 {
	if x != nil {
		return x.InfiniteLoopTimeoutTime
	}
	return 0
}

type Children struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID                int32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	NodeName          string  `protobuf:"bytes,2,opt,name=NodeName,proto3" json:"NodeName,omitempty"`
	IgnoreRestartSelf bool    `protobuf:"varint,3,opt,name=IgnoreRestartSelf,proto3" json:"IgnoreRestartSelf,omitempty"`
	WaitTime          int32   `protobuf:"varint,4,opt,name=WaitTime,proto3" json:"WaitTime,omitempty"`
	RandomDeviation   float64 `protobuf:"fixed64,5,opt,name=RandomDeviation,proto3" json:"RandomDeviation,omitempty"`
	OriginPositionKey string  `protobuf:"bytes,6,opt,name=OriginPositionKey,proto3" json:"OriginPositionKey,omitempty"`
	Radius            int32   `protobuf:"varint,7,opt,name=Radius,proto3" json:"Radius,omitempty"`
}

func (x *Children) Reset() {
	*x = Children{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Children) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Children) ProtoMessage() {}

func (x *Children) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Children.ProtoReflect.Descriptor instead.
func (*Children) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{3}
}

func (x *Children) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Children) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Children) GetIgnoreRestartSelf() bool {
	if x != nil {
		return x.IgnoreRestartSelf
	}
	return false
}

func (x *Children) GetWaitTime() int32 {
	if x != nil {
		return x.WaitTime
	}
	return 0
}

func (x *Children) GetRandomDeviation() float64 {
	if x != nil {
		return x.RandomDeviation
	}
	return 0
}

func (x *Children) GetOriginPositionKey() string {
	if x != nil {
		return x.OriginPositionKey
	}
	return ""
}

func (x *Children) GetRadius() int32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

var File_comm_proto protoreflect.FileDescriptor

var file_comm_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9d, 0x01, 0x0a,
	0x08, 0x4a, 0x53, 0x4f, 0x4e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x44, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x65, 0x73,
	0x63, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x6f, 0x72, 0x12, 0x22, 0x0a,
	0x0c, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x49, 0x44, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x49,
	0x44, 0x12, 0x19, 0x0a, 0x04, 0x52, 0x6f, 0x6f, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x05, 0x2e, 0x52, 0x6f, 0x6f, 0x74, 0x52, 0x04, 0x52, 0x6f, 0x6f, 0x74, 0x22, 0x9a, 0x01, 0x0a,
	0x04, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x65, 0x73, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x44, 0x65, 0x73, 0x63, 0x12, 0x2b, 0x0a, 0x0a, 0x44, 0x65, 0x63, 0x6f, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x44, 0x65, 0x63, 0x6f,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x0a, 0x44, 0x65, 0x63, 0x6f, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x73, 0x12, 0x25, 0x0a, 0x08, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x52,
	0x08, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x22, 0xd8, 0x01, 0x0a, 0x0a, 0x44, 0x65,
	0x63, 0x6f, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x6f, 0x64, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x46, 0x6c, 0x6f, 0x77, 0x41, 0x62, 0x6f, 0x72,
	0x74, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x46, 0x6c, 0x6f,
	0x77, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x75,
	0x6d, 0x4c, 0x6f, 0x6f, 0x70, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x4e, 0x75,
	0x6d, 0x4c, 0x6f, 0x6f, 0x70, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x49, 0x6e, 0x66, 0x69, 0x6e, 0x69,
	0x74, 0x65, 0x4c, 0x6f, 0x6f, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x49, 0x6e,
	0x66, 0x69, 0x6e, 0x69, 0x74, 0x65, 0x4c, 0x6f, 0x6f, 0x70, 0x12, 0x38, 0x0a, 0x17, 0x49, 0x6e,
	0x66, 0x69, 0x6e, 0x69, 0x74, 0x65, 0x4c, 0x6f, 0x6f, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x17, 0x49, 0x6e, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x65, 0x4c, 0x6f, 0x6f, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x22, 0xf0, 0x01, 0x0a, 0x08, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65,
	0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a,
	0x11, 0x49, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65,
	0x6c, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x49, 0x67, 0x6e, 0x6f, 0x72, 0x65,
	0x52, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x53, 0x65, 0x6c, 0x66, 0x12, 0x1a, 0x0a, 0x08, 0x57,
	0x61, 0x69, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x57,
	0x61, 0x69, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x52, 0x61, 0x6e, 0x64, 0x6f,
	0x6d, 0x44, 0x65, 0x76, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0f, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x44, 0x65, 0x76, 0x69, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x2c, 0x0a, 0x11, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x50, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x4f, 0x72,
	0x69, 0x67, 0x69, 0x6e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x52, 0x61, 0x64, 0x69, 0x75, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_comm_proto_rawDescOnce sync.Once
	file_comm_proto_rawDescData = file_comm_proto_rawDesc
)

func file_comm_proto_rawDescGZIP() []byte {
	file_comm_proto_rawDescOnce.Do(func() {
		file_comm_proto_rawDescData = protoimpl.X.CompressGZIP(file_comm_proto_rawDescData)
	})
	return file_comm_proto_rawDescData
}

var file_comm_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_comm_proto_goTypes = []interface{}{
	(*JSONData)(nil),   // 0: JSONData
	(*Root)(nil),       // 1: Root
	(*Decorators)(nil), // 2: Decorators
	(*Children)(nil),   // 3: Children
}
var file_comm_proto_depIdxs = []int32{
	1, // 0: JSONData.Root:type_name -> Root
	2, // 1: Root.Decorators:type_name -> Decorators
	3, // 2: Root.Children:type_name -> Children
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_comm_proto_init() }
func file_comm_proto_init() {
	if File_comm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_comm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JSONData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Root); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Decorators); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Children); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_comm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_comm_proto_goTypes,
		DependencyIndexes: file_comm_proto_depIdxs,
		MessageInfos:      file_comm_proto_msgTypes,
	}.Build()
	File_comm_proto = out.File
	file_comm_proto_rawDesc = nil
	file_comm_proto_goTypes = nil
	file_comm_proto_depIdxs = nil
}
