Id = "console"                                  #服务的唯一id 在集群服务下不能重复即可 建议配置文件名与服务id一致
Ip = "172.0.0.1"                                #运行主机Ip 集群通信中 按ip节点通行的查询字段 此字段可以注释掉 注释后取当前运行主机公网ip地址
Tag = "demo"                                    #服务集群标签 相同标签 且sys.registry 和 sys.rpc 配置一致 即可互相发现和通信
Type = "console"                                #服务类型 相同服务类型相同 如 多个login 服务 相同服务多开 服务类型一致
Category = "BusinessService"                    #服务类别 例如 网关服务器 或者 游戏服务器 以及普通业务服务器
Version = 1.0                                   #服务版本 多服务器相同的服务类型 高版本比低版本拥有更高的访问优先级 使用场景 热更新机制

[Settings]

# 日志系统  基础系统 每个服务默认启动
[Sys.log]
FileName = "./log/console.log"     #日志保存路径
Loglayer = 2                                #日志打印层级
Loglevel = 0                                #日志输出级别 DebugLevel:0 InfoLevel:1 WarnLevel:2 ErrorLevel:3
Debugmode = true                            #是否开启debug模式 是否输出debug日志以及输出到终端
Encoder = 0                                 #日志输出痒死 0 格式化使出 1 json样式输出
# 注册表系统 集群服务基础系统 集群服务默认启动
[Sys.registry]
RegistryType = 0                            #0:Consul 1:Nacos
Nacos_NamespaceId = "ac1b23d5-1c14-4485-9e08-f3cde8c83163"    #Nacos 的 Namespace    在RegistryType= Nacos 时生效
Nacos_NacosAddr = "172.20.27.145"           #Nacos 服务地址    在RegistryType= Nacos 时生效
Nacos_Port = 10005                          #Nacos 服务端口    在RegistryType= Nacos 时生效
Consul_Addr = "172.20.27.145:10003"         #Consul 服务地址    在RegistryType= Consul 时生效

# rpc通信系统 集群服务基础系统 集群服务默认启动
[Sys.rpc]
RPCConnType = 0                             #消息组件的类型 0 nats 1 kafka
RpcExpired = 30                             #rpc超时时长
Nats_Addr = "nats://172.20.27.145:10004"    #Nats服务地址 在RPCConnType= nats 时生效
Kafka_Host = ["172.20.27.148:9092","172.20.27.149:9092","172.20.27.150:9092"]   #kafka服务地址 在RPCConnType= kafka 时生效

[Modules.SM_ConsoleModule]
ListenPort = 9567                           #web端口
SignKey = "@234%67g12q4*67m12#4l67!"        #签名密钥 长度 24 对称加密需要固定长度密钥
RedisUrl = "172.20.27.145:10001"
RedisDB = 1
RedisPassword = "li13451234"
MongodbUrl = "mongodb://172.20.27.145:10002"
MongodbDatabase = "demo"
MailServerhost = "smtp.qq.com"
MailFromemail = "liwei1dao@foxmail.com"
MailFompasswd = "tucfnwfgmnqleaaf"
MailServerport = 587
UserInitialPassword = "88888888"            #用户初始化密码
ProjectName= "demo"
ProjectDes="lego demo 开发框架演示项目"
ProjectVersion = 1.0
ProjectTime = "2021-05-23 09:42"
[Modules.SM_ConsoleModule.ProjectMember.001] #项目成员
MemberName="李伟"
ProjectPosition="设计"
[Modules.SM_ConsoleModule.ProjectMember.002] #项目成员
MemberName="李伟"
ProjectPosition="开发"
[Modules.SM_ConsoleModule.ProjectMember.003] #项目成员
MemberName="李伟"
ProjectPosition="美术"
